### ISSUE TITLE
Adicionar item products no menu

### ISSUE THREAD

**Issue by Lu1sLima** [Lu1sPROG/spring-petclinic#7]

**Comment by Lu1sPROG** [comment]
copiei a classe petType e mudei pra product
![image](https://user-images.githubusercontent.com/50342687/66956624-16564500-f03b-11e9-857d-70f70864ba97.png)

![image](https://user-images.githubusercontent.com/50342687/66956632-19513580-f03b-11e9-935a-2982c6607f7f.png)

**Comment by Lu1sPROG** [comment]
criando nova tabela:
![image](https://user-images.githubusercontent.com/50342687/66956724-47cf1080-f03b-11e9-85dd-3d7db2859708.png)

Dropei a table products, se existisse:
![image](https://user-images.githubusercontent.com/50342687/66956858-8b297f00-f03b-11e9-934f-98f8ebeb039a.png)


Copiei a tabela de petType (types) e mudei pra products
![image](https://user-images.githubusercontent.com/50342687/66956849-85339e00-f03b-11e9-81d2-08ebb173503e.png)

**Comment by Lu1sPROG** [comment]
fui no data, e copiei o insert do types:

![image](https://user-images.githubusercontent.com/50342687/66957095-f70be780-f03b-11e9-8352-3076ee63a9b0.png)
inserindo dados no banco

**Comment by Lu1sLima** [comment]
Editando no controller:
![image](https://user-images.githubusercontent.com/50342687/66958427-8619ff00-f03e-11e9-93cc-75c99841dda4.png)
